/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Metadata } from "next";
import "@/app/(eckokit)/globals.css";
import Providers from "@/components/eckokit/providers";
import { DEFAULT_THEME } from "@/lib/themes";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import { fontVariables } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeSettings = {
    preset: (cookieStore.get("theme_preset")?.value ??
      DEFAULT_THEME.preset) as any,
    scale: (cookieStore.get("theme_scale")?.value ??
      DEFAULT_THEME.scale) as any,
    radius: (cookieStore.get("theme_radius")?.value ??
      DEFAULT_THEME.radius) as any,
  };

  const bodyAttributes = Object.fromEntries(
    Object.entries(themeSettings)
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      .filter(([_, value]) => value)
      .map(([key, value]) => [
        `data-theme-${key.replace(/([A-Z])/g, "-$1").toLowerCase()}`,
        value,
      ])
  );

  return (
    <body
      suppressHydrationWarning
      className={cn(
        "bg-background group/layout font-sans antialiased",
        fontVariables
      )}
      {...bodyAttributes}
    >
      <Providers themeSettings={themeSettings}>
        <div className="relative flex min-h-screen flex-col">{children}</div>
      </Providers>
    </body>
  );
}
